### PR TITLE
Initial version for doorstop fork under CT

### PR DESCRIPTION
**Pull request by lbiaggi**
We are planning to rely on git tags and GitHub releases to maintain the code for doorstop.

This PR proposed that when we do a tag, an automatic pipeline generates a release.

The current workflow for a release is:

1. A tag must pass the same tests from a PR before a release.
2. It needs to be able to at least be build in 3.10, 3.11 and 3.12.

### CODE REVIEW

**Review by reiterative — COMMENTED** [review]
Looks good to me, but there is an error in the Actions log. Does this need to be resolved?

**Comment by daplm** [comment]
Is there an error in how you're building the name to grab the macOS python 3.10?

**Comment by lbiaggi** [comment]
> Looks good to me, but there is an error in the Actions log. Does this need to be resolved?

Ah, apparently `pydocstyle` is broken. It seems to be an internal bug which I thought it was isolated to pyhon 3.12, but it seems not to be the case.

**Comment by lbiaggi** [comment]
> Is there an error in how you're building the name to grab the macOS python 3.10?

Nope, apparently the public macosx runner doesn't have 3.10 any more (at least in latest), which is unfortunate, as I can't maintain something simple as it is. Maybe I will drop macosx for now and reinsert it later, especially because we are not doing something that a Unix like compatible OS can't handle anyway.

What do you think @daplm @reiterative ?

**Comment by lbiaggi** [comment]
Ah, BTW, coverage is not possible to achieve 100% green right now, so please just ignore it

**Comment by daplm** [comment]
> > Is there an error in how you're building the name to grab the macOS python 3.10?
> 
> Nope, apparently the public macosx runner doesn't have 3.10 any more (at least in latest), which is unfortunate, as I can't maintain something simple as it is. Maybe I will drop macosx for now and reinsert it later, especially because we are not doing something that a Unix like compatible OS can't handle anyway.
> 
> What do you think @daplm @reiterative ?

That seems fine for now.

**Review by daplm — APPROVED** [review]
These all look fine to me for this initial version. The discussed issues with macOS can be removed for now.

**Review by daplm — APPROVED** [review]

**Comment by reiterative** [comment]
Checks are still failing on Linux - the 3.12 checks skip the ones that fail for 3.10 and 3.11 - but I don't think that this should block this initial version. Suggest that you create an issue to track that there is a know issue, and get this in.

**Review by reiterative — APPROVED** [review]

**Pull request merged**
